CREATE DATABASE SaltyDB;

USE SaltyDB;

CREATE TABLE Fighter (
	name VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE Fight (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	p1name VARCHAR(50) NOT NULL,
	p2name VARCHAR(50) NOT NULL,
	p1pot INT DEFAULT 0,
	p2pot INT DEFAULT 0,
	winner SMALLINT DEFAULT 0,
	fight_time DATETIME
) ENGINE=InnoDB;
